### PR TITLE
Keiths creations/more effects

### LINKED ISSUE #33: Newer DSP effects can't be toggled to false once they are enabled
For the Flange/Pitchshift effects, ticking the checkbox sets their "apply" values to "on" instead of "true." Also, unticking their checkboxes won't set their "apply" values back to "false"

### LINKED ISSUE #35: "std::invalid_argument" being thrown when trying to send audio
In the KeithsCreations/more_effects branch, there is currently a bug that crashes the cloud_sound binary when loading a song. More specifically, this happens as the parameters for the "pitchshift" effect are being loaded. The following error appears:

```
terminate called after throwing an instance of 'std::invalid_argument'
what(): stof
Aborted
```

### LINKED ISSUE #36: 'std::logic_error' thrown after Data parsing
The cloud_sound binary will throw an instance of 'std::logic_error' after the data gets parsed. It will list the values of all the parameters up to equalizer before reaching `Data parsed`.

Full error:
```
terminate called after throwing an instance of 'std::logic_error'
 what(): basic_string::_M_construct null not valid
Aborted
```

### PR DESCRIPTION
**Pull request by KeithsCreations**
Contains the framework for adding more DSP effects. Contains 2 new effects (flange, pitch-shifting)

### CODE REVIEW

File: AudioEngine/PacketParser.cpp [hunk 1]
```diff
@@ -146,6 +146,64 @@ void packetParser::parseData(string packet)
...
+				if (strcmp(*(it + 10), "fftsize") == 0)
+				{
+					request.pitchshift.fftsize = stof(*(it + 12));
+				}
+				if (strcmp(*(it + 14), "maxchannels") == 0)
+				{
+					request.pitchshift.maxchannels = stof(*(it + 16));
+				}
+			}
+		}
```
Comment (Arent128) [inline AudioEngine/PacketParser.cpp]: An error occurs when attempting to parse through these effects. 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stof
Aborted
Ensure that tests are written to catch these kinds of errors, or run them locally on your own device.

**Review by Arent128 — CHANGES_REQUESTED** [review]
As it stands this currently does not work as intended. This comment must be addressed before the pull request is accepted.

File: companion-app/src/Components/UploadFile.js [hunk 2]
```diff
@@ -140,7 +169,14 @@ class UploadFile extends Component {
...
         packet.parameters.echo.dry = this.state.echodry;
-        
+        packet.parameters.flange.apply = this.state.flangeapply;
+        packet.parameters.flange.mix = this.state.flangemix;
+        packet.parameters.flange.depth = this.state.flangedepth;
+        packet.parameters.flange.rate = this.state.flangerate;
+        packet.parameters.pitch.apply = this.state.pitchapply;
+        packet.parameters.pitch.pitch = this.state.pitchpitch;
+        packet.parameters.pitch.fft = this.state.pitchfft;
+        packet.parameters.pitch.channels = this.state.pitchchannels;
```
Comment (jdicarlantonio) [inline companion-app/src/Components/UploadFile.js]: The object in the javascript object's field is named "pitchshift" rather than "pitch" as is written here. This produces and error when trying to send the packet in the web app.

File: AudioEngine/PacketParser.cpp (hunk 1 above)
Comment (Arent128) [reply AudioEngine/PacketParser.cpp]: Also the arguments given from the packet don't match what is expected from the parser. 

Example: The packet send from the web-app will send this upon selecting flange and pitch shift.
'flange': {'apply': 'on', 'mix': '0.5', 'depth': '0.5', 'rate': '0.5'}, 'pitchshift': {'apply': 'on', 'pitch': '0.5', 'fftsize': 1024, 'maxchannels': 0, 'fft': '0.5', 'channels': '0.5'}}}

When on line 182 of the packetParser.cpp it appears that the parser is looking for values of "true" or "false" from the packet, but the parameters sent from the web-app are "on". Meaning when requested these effects will never get applied.


Lastly, the web app has a bug that occurs when you select the flange and pitch shift effects. If you select them the first time they go from "false" to "on" when you send a packet. However, If you remove the effects from selection and send the packet again they are still set to "on" in the data packet. Here are some screenshots of this occuring.
effects_bug_1
effects_bug_2

Comment (KeithsCreations) [reply AudioEngine/PacketParser.cpp]: Can you verify if the "false to on" issue only happens on the flange/pitch effects, and not on the echo/eq effects? I based the code for the new effects on what was already written before.

Comment (KeithsCreations) [reply AudioEngine/PacketParser.cpp]: > Can you verify if the "false to on" issue only happens on the flange/pitch effects, and not on the echo/eq effects? I based the code for the new effects on what was already written before.

I just verified that this issue only effects the newer effects. Putting this issue up.

File: companion-app/src/Components/UploadFile.js [hunk 3]
```diff
@@ -240,6 +276,38 @@ class UploadFile extends Component {
         this.setState({ echodry: event.target.value });
       }
 
+      applyFlange(event) {
+        this.setState({ flangeapply: event.target.value });
+      }
```
Comment (jdicarlantonio) [inline companion-app/src/Components/UploadFile.js]: This will set the value for apply to either "on" or "off". Check out the applyEq() and applyEcho() functions. You can see if the checkbox is checked or not using ```event.target.checked```. From there you just set the value to true or false.

**Comment by KeithsCreations** [comment]
Due to segmentation faults occurring with pitchshift, it has been removed for now. All of its associated work has been moved to the sandbox folder.

**Review by jdicarlantonio — APPROVED** [review]

**Review by Arent128 — APPROVED** [review]

**Review by blim012 — APPROVED** [review]
